---
title: "nueralNet"
author: "Jacob Mitchell"
date: "4/15/2022"
output: html_document
---

## Lasso Regression on Imputed Data

```{r setup}
rm(list = ls())
source("/Users/jacobmitchell/Documents/STAT6440/functions/myfunctions.R")
hospital <- read.csv("/Users/jacobmitchell/Documents/STAT6440/csvs/dataset_mice_output.csv")
hospital$hospital_death <- as.factor(hospital$hospital_death)
levels(hospital$hospital_death) <- c("0", "1")
hospital = subset(hospital, select = -c(apache_4a_hospital_death_prob, apache_4a_icu_death_prob))
```

## R Markdown


```{r cars}
vals <- unique(hospital$ethnicity)
hospital$ethnicity <- as.factor(hospital$ethnicity)
hospital$ethnicity <- ifelse(hospital$ethnicity == "Caucasian", 1, hospital$ethnicity)
hospital$gender <- as.factor(hospital$gender)
hospital$gender <- ifelse(hospital$ethnicity == "M", 0, hospital$gender)
hospital$gender <- ifelse(hospital$ethnicity == "F", 1, hospital$gender)
hospital$icu_admit_source <- as.factor(hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Accident & Emergency", 0, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Operating Room / Recovery", 1, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Floor", 2, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Other Hospital", 3, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Other ICU", 4, hospital$icu_admit_source)
hospital$icu_stay_type <- as.factor(hospital$icu_stay_type)
hospital$icu_stay_type <- ifelse(hospital$icu_stay_type == "admit", 0, hospital$icu_stay_type)
hospital$icu_stay_type <- ifelse(hospital$icu_stay_type == "readmit", 1, hospital$icu_stay_type)
hospital$icu_stay_type <- ifelse(hospital$icu_stay_type == "transfer", 2, hospital$icu_stay_type)
hospital$icu_type <- as.factor(hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "Med-Surg ICU", 0, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "MICU", 1, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "CTICU", 2, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "CCU-CTICU", 3, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "Neuro ICU", 4, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "SICU", 5, hospital$icu_type)
hospital$apache_3j_bodysystem <- as.factor(hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Cardiovascular", 0, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Metabolic", 1, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Nuerological", 2, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Gastrointestinal", 3, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Metabolic", 4, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Musculoskeletal/Skin", 5, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Respiratory", 6, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Trauma", 7, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Genitourinary", 8, hospital$apache_3j_bodysystem)
hospital$apache_2_bodysystem <- as.factor(hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Cardiovascular", 0, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Metabolic", 1, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Nuerological", 2, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Gastrointestinal", 3, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Metabolic", 4, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Musculoskeletal/Skin", 5, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Respiratory", 6, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Trauma", 7, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Genitourinary", 8, hospital$apache_2_bodysystem)
```

## Including Plots

```{r pressure, echo=FALSE}
RNGkind(sample.kind = "Rounding")
set.seed(0) ## set seed so that you get same partition each time
p2 <- partition.2(hospital, 0.7) ## creating 70:30 partition
training.data <- p2$data.train
test.data <- p2$data.test
```

```{r LassoReg}
library(glmnet)
library(caret)
set.seed(0)
train_control <- trainControl(method="cv", number=10)
# convert data to matrix type
trainX <- as.matrix(training.data[, -81])
testX <- as.matrix(test.data[, -81])
trainY <- training.data$hopsital_death
glmnet.lasso <- train(hospital_death ~ ., data = training.data, method = "glmnet",metric = "Kappa",
                      family = "binomial", trControl = train_control, 
                      tuneGrid = expand.grid(alpha = 1,lambda = seq(0.001,0.1,by = 0.001)))

```

```{r prediction}
pred.prob.lasso <- predict(glmnet.lasso, s = glmnet.lasso$bestTune, test.data, type = "prob")
pred.y.lasso <- ifelse(pred.prob.lasso[,2] > 0.2, "1", "0") # using cutoff = 0.25
confusionMatrix(as.factor(pred.y.lasso), as.factor(test.data$hospital_death), 
                positive = "0")
```

## On NonImputed Data

```{r normalData}
rm(list = ls())
source("/Users/jacobmitchell/Documents/STAT6440/functions/myfunctions.R")
hospital <- read.csv("/Users/jacobmitchell/Documents/STAT6440/csvs/dataset.csv")
hospital$hospital_death <- as.factor(hospital$hospital_death)
levels(hospital$hospital_death) <- c("0", "1")
hospital = subset(hospital, select = -c(apache_4a_hospital_death_prob, apache_4a_icu_death_prob))
vals <- unique(hospital$ethnicity)
hospital$ethnicity <- as.factor(hospital$ethnicity)
hospital$ethnicity <- ifelse(hospital$ethnicity == "Caucasian", 1, hospital$ethnicity)
hospital$gender <- as.factor(hospital$gender)
hospital$gender <- ifelse(hospital$ethnicity == "M", 0, hospital$gender)
hospital$gender <- ifelse(hospital$ethnicity == "F", 1, hospital$gender)
hospital$icu_admit_source <- as.factor(hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Accident & Emergency", 0, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Operating Room / Recovery", 1, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Floor", 2, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Other Hospital", 3, hospital$icu_admit_source)
hospital$icu_admit_source <- ifelse(hospital$icu_admit_source == "Other ICU", 4, hospital$icu_admit_source)
hospital$icu_stay_type <- as.factor(hospital$icu_stay_type)
hospital$icu_stay_type <- ifelse(hospital$icu_stay_type == "admit", 0, hospital$icu_stay_type)
hospital$icu_stay_type <- ifelse(hospital$icu_stay_type == "readmit", 1, hospital$icu_stay_type)
hospital$icu_stay_type <- ifelse(hospital$icu_stay_type == "transfer", 2, hospital$icu_stay_type)
hospital$icu_type <- as.factor(hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "Med-Surg ICU", 0, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "MICU", 1, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "CTICU", 2, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "CCU-CTICU", 3, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "Neuro ICU", 4, hospital$icu_type)
hospital$icu_type <- ifelse(hospital$icu_type == "SICU", 5, hospital$icu_type)
hospital$apache_3j_bodysystem <- as.factor(hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Cardiovascular", 0, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Metabolic", 1, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Nuerological", 2, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Gastrointestinal", 3, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Metabolic", 4, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Musculoskeletal/Skin", 5, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Respiratory", 6, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Trauma", 7, hospital$apache_3j_bodysystem)
hospital$apache_3j_bodysystem <- ifelse(hospital$apache_3j_bodysystem == "Genitourinary", 8, hospital$apache_3j_bodysystem)
hospital$apache_2_bodysystem <- as.factor(hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Cardiovascular", 0, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Metabolic", 1, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Nuerological", 2, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Gastrointestinal", 3, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Metabolic", 4, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Musculoskeletal/Skin", 5, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Respiratory", 6, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Trauma", 7, hospital$apache_2_bodysystem)
hospital$apache_2_bodysystem <- ifelse(hospital$apache_2_bodysystem == "Genitourinary", 8, hospital$apache_2_bodysystem)
```

```{r looking}
library(tidyr)
hospital = subset(hospital, select = -c(X))
hospital <- drop_na(hospital)
```

```{r more}
RNGkind(sample.kind = "Rounding")
set.seed(0) ## set seed so that you get same partition each time
p2 <- partition.2(hospital, 0.7) ## creating 70:30 partition
training.data <- p2$data.train
test.data <- p2$data.test
```

```{r LassoReg2}
library(glmnet)
library(caret)
set.seed(0)
train_control <- trainControl(method="cv", number=10)
# convert data to matrix type
trainX <- as.matrix(training.data[, -82])
testX <- as.matrix(test.data[, -82])
trainY <- training.data$hopsital_death
glmnet.lasso <- train(hospital_death ~ ., data = training.data, method = "glmnet",metric = "Kappa",
                      family = "binomial", trControl = train_control, 
                      tuneGrid = expand.grid(alpha = 1,lambda = seq(0.001,0.1,by = 0.001)))
```

```{r prediction}
pred.prob.lasso <- predict(glmnet.lasso, s = glmnet.lasso$bestTune, test.data, type = "prob")
pred.y.lasso <- ifelse(pred.prob.lasso[,2] > 0.2, "1", "0") # using cutoff = 0.25
confusionMatrix(as.factor(pred.y.lasso), as.factor(test.data$hospital_death), 
                positive = "0")
```